cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
before_script:
  - whoami && pwd && date
stages:
  - build
  - test
  - staging
  - production

# build (all branchs) = update_libs + build 
job_build:
  stage: build
  script: 
    - pwd
    - yarn install
    - cp config.example.json config.json
    - yarn run build
    
# test (all branchs) = lint + test 
job_test:
  stage: test
  script: 
    - pwd
    - yarn run lint
    - yarn run test

# staging( only dev branch )  = deploy
job_deploy_staging:
  stage: staging
  only:    
    - staging
#  when: manual
  script: 
    - pwd
    - cp config.staging.example.json config.json
    - yarn run build
    - cp pm2.staging.example.json ./dist/pm2.json
    - ln -sfn $(pwd)/node_modules/ ./dist/node_modules
    - cd ./dist
    - echo cp -r "$(pwd)" "$STAGING_SERVER_DIR/build-$CI_JOB_ID"
    - cp -r "$(pwd)" "$STAGING_SERVER_DIR/build-$CI_JOB_ID"
    - echo ln -sfn $STAGING_SERVER_DIR/build-$CI_JOB_ID $STAGING_SERVER_DIR/current
    - ln -sfn $STAGING_SERVER_DIR/build-$CI_JOB_ID $STAGING_SERVER_DIR/current
    - echo cd $STAGING_SERVER_DIR/current
    - cd $STAGING_SERVER_DIR/current
    - pm2 delete api_server_staging
    - pm2 start pm2.json